version: '3.1'

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: